### ISSUE TITLE
add support for end_of_line

### ISSUE THREAD

**Issue by dmahugh** [Microsoft/vscode-editorconfig#11]
Would be helpful to be able to explicitly set EOL default - for example, set to LF when you're developing on Windows but know that most of your deployments will be on Linux.

Per discussion with Alex, would need to first add the relevant extension API in vscode (to change document EOL) and then add support for it in the editorconfig extension.

**Comment by harriha** [comment]
Linking this here for tracking purposes: the relevant VS Code issue is probably this https://github.com/Microsoft/vscode/issues/1546

The line ending configuration (or lack of it) in VS Code is a quite annoying shortcoming, thus :+1: for getting this implemented as soon as possible.

**Comment by SteveALee** [comment]
+1
Please prioritise this

**Comment by PEKTOP** [comment]
+1

**Comment by harriha** [comment]
The latest VS Code update seems to have finally the support for `files.eol` config - I assume this issue isn't blocked anymore?

Ping @SamVerschueren @jedmao et al, since this is the issue tracker for the deprecated extension, would it make sense to move all the relevant issues from here to the [new repository](https://github.com/editorconfig/editorconfig-vscode)?

**Comment by SamVerschueren** [comment]
Copied the issue. All issues not being resolved yet in the new repository can be copied over.

Yes VS Code has support for `files.eol`, but it's not possible to set that on the fly per texteditor. So I'm afraid it's not yet enough.

**Comment by harriha** [comment]
Aw damn, I thought there would be direct mapping between public config options and internal config APIs. But thanks for the update, let's see if (or when) this becomes possible.
