### ISSUE TITLE
Any intention of merging this effort with editorconfig/editorconfig-vscode?

### ISSUE THREAD

**Issue by rhbecker** [Microsoft/vscode-editorconfig#23]
Seems like forces could join together for one super effort?

https://github.com/editorconfig/editorconfig-vscode/issues/11

**Comment by jedmao** [comment]
It's up to Microsoft, but I'm open to the idea of a "transfer ownership" if we can clear up some confusion or updating the readme to deprecate this one in favor of the more-maintained one.

**Comment by egamma** [comment]
(Chiming in since @chrisdias  is out.)

@rhbecker @jedmao we have implemented vscode-editorconfig and several other extensions to validate the extension API. The goal is to give users a great editorconfig extension that is actively maintained. We just need to coordinate the transition and how to deprecate the existing one. For example:
- document the editorconfig extension situation in the Readme of the existing extension
- do one more update to the existing editorconfig extension that informs users (shows an info message on activation) to migrate to the other extension.

Other ideas?

**Comment by jedmao** [comment]
@egamma, that's exactly how I would do it.

**Comment by egamma** [comment]
OK - then let's discuss this with @chrisdias when he is back next week.

**Comment by chrisdias** [comment]
:+1: on the plan, will work on this after skiing :)

**Comment by chrisdias** [comment]
updated readme...  still need to update extension.

**Comment by jedmao** [comment]
Readme updated on my end too: https://github.com/editorconfig/editorconfig-vscode/commit/e625d829629bca4180aae2f74dff35ee31377288

**Comment by chrisdias** [comment]
With a74f6778864445b58c63f42dca906f3b359d280f we now show an informational prompt with a link to the readme, which tells folks to uninstall this extension and install the latest from editorconfig !

**Comment by jedmao** [comment]
Thanks @chrisdias! I just tested everything out and I think this is a very good way to inform the user.
